version: '3.8'

services:
  birb-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Birb Nest API URL
      BIRB_NEST_URL: ${BIRB_NEST_URL:-http://birb-nest-api:8080}
      # Write interval in seconds
      WRITE_INTERVAL: ${WRITE_INTERVAL:-3}
      # Log level (debug, info, warn, error)
      LOG_LEVEL: ${LOG_LEVEL:-info}
    restart: unless-stopped
    networks:
      - birb-net
    deploy:
      replicas: 3

networks:
  birb-net:
    external: true